---
version: '2.4'

services:
  rd-professional-api:
    image:  'hmctspublic.azurecr.io/rd/professional-api:latest'
    environment:
      POSTGRES_HOST: ccd-shared-database
      POSTGRES_USERNAME: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_PORT: 5432
      S2S_MICROSERVICE: rd_professional_api
      S2S_SECRET: "${OAUTH2_CLIENT_RD_PROFESSIONAL}"
      S2S_URL: http://service-auth-provider-api:8080
      idam_url: http://idam-api:5000
      LD_SDK_KEY: sdk-b1310c4a-e522-4512-9e68-d75d23b04c5d
      ACTIVE_ORG_EXT: "true"
      ROOT_LOGGING_LEVEL: debug
      OIDC_ISSUER_URL: http://fr-am:8080/openam/oauth2/hmcts
      OPEN_ID_API_BASE_URI: http://idam-web-public:8080/o
      USER_PROFILE_URL: http://rd-user-profile-api:8091
      PRD_S2S_AUTHORISED_SERVICES: civil_service,xui_webapp_mo,rd_professional_api,rd_user_profile_api,xui_webapp,finrem_payment_service,fpl_case_service,iac,aac_manage_case_assignment,civil_general_applications,cmc,cmc_claim_store
    ports:
      - 8090:8090
    networks:
      - ccd-network
networks:
  ccd-network:
    external: true
