---
version: '2.4'
services:
  ccd-message-publisher:
    image: "hmctspublic.azurecr.io/ccd/message-publisher:latest"
    container_name: message-publisher
    environment:
      DATA_STORE_DB_HOST: ccd-shared-database
      DATA_STORE_DB_PORT: 5432
      DATA_STORE_DB_USERNAME: "${DB_USERNAME}"
      DATA_STORE_DB_PASSWORD: "${DB_PASSWORD}"
      SERVICE_BUS_CONNECTION_STRING: "${AZURE_SERVICE_BUS_CONNECTION_STRING}"
      CCD_CASE_EVENTS_DESTINATION: "${AZURE_SERVICE_BUS_TOPIC_NAME}"
    ports:
      - 4456:4456

  camunda-bpm:
    image: "hmctsprivate.azurecr.io/camunda/bpm:latest"
    container_name: camunda-bpm
    environment:
      CAMUNDA_NEXUS_USER: "${WA_CAMUNDA_NEXUS_USER}"
      CAMUNDA_NEXUS_PASSWORD: "${WA_CAMUNDA_NEXUS_PASSWORD}"
      CAMUNDA_DB_HOST: ccd-shared-database
      CAMUNDA_DB_PORT: 5432
      CAMUNDA_DB_USER_NAME: "${DB_USERNAME}"
      CAMUNDA_DB_PASSWORD: "${DB_PASSWORD}"
      camunda.bpm.database.schema-update: "true"
      CAMUNDA_API_AUTH_ENABLED: "true"
      S2S_URL: http://service-auth-provider-api:8080
      camundaGroups.work-allocation.s2sServiceNames: wa_task_management_api,wa_workflow_api,wa_case_event_handler,wa_camunda_pipeline_upload
      WA_AUTO_CONFIGURE_TASKS_ENABLED: "true"
      TASK_MANAGEMENT_API_URL: "http://wa-task-management-api:8087"
      TZ: Europe/London
    ports:
      - 8999:8999
    depends_on:
      - ccd-shared-database
      - service-auth-provider-api
    links:
      - ccd-shared-database
      - service-auth-provider-api

  wa-workflow-api:
    image: "hmctspublic.azurecr.io/wa/workflow-api:latest"
    container_name: workflow-api
    environment:
      CAMUNDA_URL: http://camunda-bpm:8999/engine-rest
      S2S_URL: http://service-auth-provider-api:8080
      S2S_SECRET_WORKFLOW_API: "AAAAAAAAAAAAAAAA"
      POSTGRES_HOST: ccd-shared-database
      POSTGRES_PORT: 5432
      POSTGRES_NAME: wa_workflow_api
      POSTGRES_USERNAME: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      WA_S2S_AUTHORIZED_SERVICES: wa_workflow_api,wa_case_event_handler,camunda-bpm,xui_webapp
      LAUNCH_DARKLY_SDK_KEY: sdk-28c71191-54b1-4d81-8c8d-add52b134bc7
    ports:
      - 8099:8099
    depends_on:
      - ccd-shared-database
      - service-auth-provider-api
      - camunda-bpm
    links:
      - ccd-shared-database
      - service-auth-provider-api
      - camunda-bpm

  wa-task-management-api:
    image: "hmctspublic.azurecr.io/wa/task-management-api:latest"
    container_name: wa-task-management-api
    environment:
      CAMUNDA_URL: http://camunda-bpm:8999/engine-rest
      S2S_URL: http://service-auth-provider-api:8080
      IDAM_URL: http://sidam-simulator:5000
      CCD_URL: http://ccd-data-store-api:4452
      POSTGRES_HOST: ccd-shared-database
      OPEN_ID_IDAM_URL: http://sidam-simulator:5000
      ROLE_ASSIGNMENT_URL: http://am-role-assignment-service:4096
      POSTGRES_PORT: 5432
      POSTGRES_NAME: cft_task_db
      ALLOWED_JURISDICTIONS: wa,ia,sscs,civil
      ALLOWED_CASE_TYPES: asylum,wacasetype,sscs,civil
      WA_S2S_AUTHORIZED_SERVICES: ccd,ccd_data,ccd_gw,ccd_ps,iac,wa_task_management_api,xui_webapp,wa_task_monitor,camunda_bpm,wa_workflow_api
      LAUNCH_DARKLY_SDK_KEY: sdk-28c71191-54b1-4d81-8c8d-add52b134bc7
      WA_SYSTEM_USERNAME: "${WA_SYSTEM_USERNAME}"
      WA_SYSTEM_PASSWORD: "${WA_SYSTEM_PASSWORD}"
    ports:
      - 8087:8087
    depends_on:
      - ccd-shared-database
      - service-auth-provider-api
      - camunda-bpm

  case-event-handler:
    image: "hmctspublic.azurecr.io/wa/case-event-handler:latest"
    container_name: case-event-handler
    environment:
      POSTGRES_HOST: ccd-shared-database
      AZURE_SERVICE_BUS_CONNECTION_STRING: "${AZURE_SERVICE_BUS_CONNECTION_STRING}"
      AZURE_SERVICE_BUS_TOPIC_NAME: "${AZURE_SERVICE_BUS_TOPIC_NAME}"
      AZURE_SERVICE_BUS_SUBSCRIPTION_NAME: "${AZURE_SERVICE_BUS_SUBSCRIPTION_NAME}"
      AZURE_SERVICE_BUS_CCD_CASE_EVENTS_SUBSCRIPTION_NAME: "${AZURE_SERVICE_BUS_CCD_CASE_EVENTS_SUBSCRIPTION_NAME}"
      POSTGRES_CONNECTION_OPTIONS: "?stringtype=unspecified&gssEncMode=disable"
      APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=00000000-0000-0000-0000-000000000000"
      ENVIRONMENT: "local"
      S2S_URL: http://service-auth-provider-api:8080
      WA_WORKFLOW_API_URL: http://wa-workflow-api:8099
      OPEN_ID_IDAM_URL: http://sidam-simulator:5000
      IDAM_URL: http://sidam-simulator:5000
      ROLE_ASSIGNMENT_URL: http://am-role-assignment-service:4096
      CAMUNDA_URL: http://camunda-bpm:8999/engine-rest
      CCD_URL: http://ccd-data-store-api:4452
      AZURE_SERVICE_BUS_FEATURE_TOGGLE: "true"
      AZURE_SERVICE_BUS_DLQ_FEATURE_TOGGLE: "true"
      AZURE_SERVICE_BUS_CONCURRENT_SESSIONS: 2
      MESSAGE_PROCESSING_POLL_INTERVAL_MILLISECONDS: 2000
      MESSAGE_PROCESSING_THREAD_POOL_SIZE: 5
      MESSAGE_READINESS_POLL_INTERVAL_MILLISECONDS: 500
      MESSAGE_READINESS_THREAD_POOL_SIZE: 2
      LAUNCH_DARKLY_SDK_KEY: sdk-28c71191-54b1-4d81-8c8d-add52b134bc7
    ports:
      - 8088:8088
    depends_on:
      - ccd-shared-database
      - service-auth-provider-api
      - camunda-bpm
      - am-role-assignment-service
      - wa-workflow-api

  wa-task-monitor:
    image: "hmctspublic.azurecr.io/wa/task-monitor:latest"
    container_name: wa-task-monitor
    environment:
      S2S_URL: http://service-auth-provider-api:8080
      WA_WORKFLOW_API_URL: http://wa-workflow-api:8099
      OPEN_ID_IDAM_URL: http://sidam-simulator:5000
      IDAM_URL: http://sidam-simulator:5000
      ROLE_ASSIGNMENT_URL: http://am-role-assignment-service:4096
      CAMUNDA_URL: http://camunda-bpm:8999/engine-rest
      CCD_URL: http://ccd-data-store-api:4452
      TASK_MANAGEMENT_SERVICE_URL: http://wa-task-management-api:8087
      CASE_EVENT_HANDLER_SERVICE_URL: http://wa-case-event-handler:8088
      CCD_SEARCH_URL: http://ccd-elasticsearch:9200
      CONFIGURATION_CAMUNDA_MAX_RESULTS: 100
      CONFIGURATION_TIME_LIMIT_FLAG: "true"
      CONFIGURATION_TIME_LIMIT: 1440
      INITIATION_CAMUNDA_MAX_RESULTS: 100
      INITIATION_TIME_LIMIT_FLAG: "true"
      INITIATION_TIME_LIMIT: 120
      TERMINATION_CAMUNDA_MAX_RESULTS: 100
      TERMINATION_TIME_LIMIT_FLAG: "true"
      TERMINATION_TIME_LIMIT: 120
      PENDING_TERMINATION_CAMUNDA_MAX_RESULTS: 1
      WA_SYSTEM_USERNAME: "${WA_SYSTEM_USERNAME}"
      WA_SYSTEM_PASSWORD: "${WA_SYSTEM_PASSWORD}"
    ports:
      - 8077:8077
    depends_on:
      - service-auth-provider-api
      - case-event-handler
      - wa-task-management-api
      - ccd-elasticsearch
      - am-role-assignment-service
