---
version: '2.4'

services:
  xui:
    image: "hmctspublic.azurecr.io/xui/webapp:latest"
    environment:
      MICROSERVICE: xui_webapp
      PROTOCOL: http
      XUI_ENV: local

      SERVICES_CCD_COMPONENT_API: http://ccd-api-gateway:3453
      SERVICES_CCD_DATA_STORE_API: http://ccd-data-store-api:4452
      SERVICES_DOCUMENTS_API: http://dm-store:8080
      SERVICES_DOCUMENTS_API_V2: http://ccd-case-document-am-api:4455
      SERVICES_S2S: http://service-auth-provider-api:8080
      SERVICES_IDAM_LOGIN_URL: "${IDAM_STUB_LOCALHOST:-http://localhost:3501}"
      SERVICES_IDAM_API_URL: "${IDAM_STUB_SERVICE_NAME:-http://idam-api:5000}"
      SERVICES_IDAM_INDEX_URL: /
      SERVICES_IDAM_OAUTH_CALLBACK_URL: /oauth2/callback
      SERVICES_IDAM_CLIENT_ID: xui_webapp
      SERVICES_PAYMENTS_URL: http://wiremock:8080
      SERVICES_PRD_API: http://wiremock:8080
      SERVICES_PRD_COMMONDATA_API: http://wiremock:8080
      SERVICES_PRD_API_URL: http://wiremock:8080
      SERVICES_LOCATION_REF_API_URL: http://wiremock:8080
      SERVICES_PRD_JUDICIAL_API: http://wiremock:8080
      SERVICES_PRD_LOCATION_API: http://wiremock:8080

      SERVICES_EM_ANNO_API: http://ccd-api-gateway:3453
      REDISCLOUD_URL: http://dummyrediscloudurl
      SERVICES_ROLE_ASSIGNMENT_API: http://am-role-assignment-service:4096
      SERVICES_CCD_CASE_ASSIGNMENT_API: http://manage-case-assignment:4454
      SERVICES_HEARINGS_COMPONENT_API_CIVIL: http://localhost:4000

      #LAUNCH_DARKLY_CLIENT_ID must be set to enable share a case functionality
      LAUNCH_DARKLY_CLIENT_ID: 5de6610b23ce5408280f2268

      FEATURE_REDIS_ENABLED: "false"
      FEATURE_APP_INSIGHTS_ENABLED: "false"
      FEATURE_SECURE_COOKIE_ENABLED: "false"
      FEATURE_WORKALLOCATION_ENABLED: "false"
      FEATURE_PROXY_ENABLED: "false"
      WA_SUPPORTED_JURISDICTIONS: "IA,PRIVATELAW"
      APPINSIGHTS_INSTRUMENTATIONKEY: fake

      S2S_SECRET:  "${IDAM_KEY_XUI_WEBAPP}"
      IDAM_SECRET: "${OAUTH2_CLIENT_XUI}"

      JURISDICTIONS: "CIVIL"

      SYSTEM_USER_NAME: "dummy"
      SYSTEM_USER_PASSWORD: "dummy"

    ports:
      - 3333:3000
    depends_on:
      ccd-data-store-api:
        condition: service_started
    networks:
      - ccd-network

networks:
  ccd-network:
    external: true
